//
//  Detection.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.23
//


#import "Detection.h"
//#import "NoSQLSampleDataGenerator.h"
#import <AWSAuthCore/AWSAuthCore.h>
#import <sys/utsname.h>


@implementation Detection

+ (NSString *)dynamoDBTableName {

    return @"shuiguang-mobilehub-1086816736-detection";
}

+ (NSString *)hashKeyAttribute {

    return @"_detectionId";
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
               @"_detectionId" : @"detection_id",
               @"_bodyArea" : @"body_area",
               @"_dateTime" : @"date_time",
               @"_nursingStatus" : @"nursing_status",
               @"_userId" : @"user_id",
               @"_value" : @"value",
             };
}

@end
