//
//  Detection.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.23
//

#import <UIKit/UIKit.h>
#import <AWSDynamoDB/AWSDynamoDB.h>

//#import "NoSQLModelHelpers.h"

NS_ASSUME_NONNULL_BEGIN


@interface Detection : AWSDynamoDBObjectModel <AWSDynamoDBModeling>

+ (NSDictionary *)JSONKeyPathsByPropertyKey;

@property (nonatomic, strong) NSString *_detectionId;
@property (nonatomic, strong) NSString *_bodyArea;
@property (nonatomic, strong) NSString *_dateTime;
@property (nonatomic, strong) NSString *_nursingStatus;
@property (nonatomic, strong) NSString *_userId;
@property (nonatomic, strong) NSString *_value;

@end

NS_ASSUME_NONNULL_END
