//
//  USER.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.23
//


#import <UIKit/UIKit.h>
#import <AWSDynamoDB/AWSDynamoDB.h>

//#import "NoSQLModelHelpers.h"

NS_ASSUME_NONNULL_BEGIN


@interface USER : AWSDynamoDBObjectModel <AWSDynamoDBModeling>

+ (NSDictionary *)JSONKeyPathsByPropertyKey;

@property (nonatomic, strong) NSString *_userId;
@property (nonatomic, strong) NSString *_dateOfBirth;
@property (nonatomic, strong) NSString *_email;
@property (nonatomic, strong) NSString *_facebook;
@property (nonatomic, strong) NSString *_gender;
@property (nonatomic, strong) NSString *_google;
@property (nonatomic, strong) NSString *_phone;
@property (nonatomic, strong) NSString *_platform;
@property (nonatomic, strong) NSString *_username;
@property (nonatomic, strong) NSString *_wechat;
@end

NS_ASSUME_NONNULL_END
