//
//  USER.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.23
//


#import "USER.h"
//#import "NoSQLSampleDataGenerator.h"
#import <AWSAuthCore/AWSAuthCore.h>
#import <sys/utsname.h>


@implementation USER

+ (NSString *)dynamoDBTableName {

    return @"shuiguang-mobilehub-1086816736-USER";
}

+ (NSString *)hashKeyAttribute {

    return @"_userId";
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"_userId" : @"userId",
             @"_dateOfBirth" : @"date_of_birth",
             @"_email" : @"email",
             @"_facebook" : @"facebook",
             @"_gender" : @"gender",
             @"_google" : @"google",
             @"_phone" : @"phone",
             @"_platform" : @"platform",
             @"_username" : @"username",
             @"_wechat" : @"wechat",
             };
}

@end
